# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [10]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [11]:
import tensorflow as tf
print(tf.__version__)

2.4.1


### Set random seed

In [12]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [13]:
from sklearn.datasets import load_iris
data = load_iris()

In [7]:
data

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [14]:
import pandas as pd
df = pd.DataFrame(data.data, columns=data.feature_names)
df['class']=data.target
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  class
0                5.1               3.5  ...               0.2      0
1                4.9               3.0  ...               0.2      0
2                4.7               3.2  ...               0.2      0
3                4.6               3.1  ...               0.2      0
4                5.0               3.6  ...               0.2      0

[5 rows x 5 columns]

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [15]:
from sklearn.model_selection import train_test_split
X = df.iloc[:,0:4]
y = df.iloc[:, 4]

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state = 54)

In [61]:
# printing the shape of train and test sets

print('Train shape',(X_train.shape))
print('Test Shape',(X_test.shape))
print('Train class shape',(y_train.shape))
print('Test class shape',(y_test.shape))

Train shape (112, 4)
Test Shape (38, 4)
Train class shape (112,)
Test class shape (38,)


## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [18]:
train_y = tf.keras.utils.to_categorical(y_train, num_classes=3)
test_y = tf.keras.utils.to_categorical(y_test, num_classes=3)
train_y
test_y

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.]], dtype=float32)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [19]:
model = tf.keras.models.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [21]:
model.add(tf.keras.layers.Dense(3,input_shape=(4,), activation='softmax'))

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 12        
Total params: 27
Trainable params: 27
Non-trainable params: 0
_________________________________________________________________


## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [23]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 12        
Total params: 27
Trainable params: 27
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [25]:
model_checkpoint = tf.keras.callbacks.ModelCheckpoint('lab1.h5', save_best_only=True, monitor='val_accuracy', mode='max', verbose=1)

In [26]:
model.fit(X_train, train_y,validation_data=(X_test,test_y),epochs=200,callbacks=[model_checkpoint])

Epoch 1/200
4/4 [==============================] - 3s 64ms/step - loss: 1.1485 - accuracy: 0.3192 - val_loss: 1.1354 - val_accuracy: 0.3684

Epoch 00001: val_accuracy improved from -inf to 0.36842, saving model to lab1.h5
Epoch 2/200
4/4 [==============================] - 0s 12ms/step - loss: 1.1359 - accuracy: 0.3400 - val_loss: 1.1314 - val_accuracy: 0.3684

Epoch 00002: val_accuracy did not improve from 0.36842
Epoch 3/200
4/4 [==============================] - 0s 11ms/step - loss: 1.1540 - accuracy: 0.2817 - val_loss: 1.1272 - val_accuracy: 0.3684

Epoch 00003: val_accuracy did not improve from 0.36842
Epoch 4/200
4/4 [==============================] - 0s 11ms/step - loss: 1.1339 - accuracy: 0.3067 - val_loss: 1.1232 - val_accuracy: 0.3684

Epoch 00004: val_accuracy did not improve from 0.36842
Epoch 5/200
4/4 [==============================] - 0s 11ms/step - loss: 1.1272 - accuracy: 0.3150 - val_loss: 1.1193 - val_accuracy: 0.3684

Epoch 00005: val_accuracy did not improve from 0.

In [27]:
model.save('lab1-v1.h5')

## Question 10

### Make predictions
- Predict labels on one row

In [28]:
model = tf.keras.models.load_model('lab1-v1.h5')

In [29]:
model.input

<KerasTensor: shape=(None, 4) dtype=float32 (created by layer 'dense_input')>

In [30]:
print(X_test[:1].shape)
model.predict(X_test[:1])

(1, 4)


array([[0.78712225, 0.14781037, 0.06506748]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [31]:
import numpy as np
print(data.target_names[np.argmax(model.predict(X_test[:1]))])

setosa




---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [ ]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [ ]:
import tensorflow as tf
print(tf.__version__)

### Set random seed

In [ ]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [33]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

In [35]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [36]:
import pandas as pd
data=pd.read_csv('/content/drive/MyDrive/lab 6 nueral networks/prices.csv')

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   date    851264 non-null  object 
 1   symbol  851264 non-null  object 
 2   open    851264 non-null  float64
 3   close   851264 non-null  float64
 4   low     851264 non-null  float64
 5   high    851264 non-null  float64
 6   volume  851264 non-null  float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB


In [38]:
data.drop(['date', 'symbol'], axis=1, inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 5 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   open    851264 non-null  float64
 1   close   851264 non-null  float64
 2   low     851264 non-null  float64
 3   high    851264 non-null  float64
 4   volume  851264 non-null  float64
dtypes: float64(5)
memory usage: 32.5 MB


## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [39]:
data = data[:1000]
data.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [40]:
data.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

In [41]:
df_features = data.iloc[:,0:4]
df_label = data.iloc[:,4]

df_label = df_label / 1000000

In [43]:
df_label

0       2.1636
1       2.3864
2       2.4895
3       2.0063
4       1.4086
        ...   
995     2.1332
996     1.9824
997    37.1528
998     6.5686
999     5.6043
Name: volume, Length: 1000, dtype: float64

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [44]:
df_features = np.array(df_features)

df_label = np.array(df_label)

df_features = df_features.astype('float32')
df_label = df_label.astype('float32')
print('feature type',df_features.dtype,'Type of lables',df_label.dtype)


feature type float32 Type of lables float32


## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [46]:
X = tf.math.l2_normalize(df_features)
X

<tf.Tensor: shape=(1000, 4), dtype=float32, numpy=
array([[0.02202893, 0.02245905, 0.02182904, 0.02253223],
       [0.02235197, 0.0214132 , 0.02140606, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051191, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.00799559, 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [47]:
w = tf.zeros((4,1), dtype=tf.dtypes.float32)
b = tf.zeros((1))


In [49]:
print(w)
print(b)

tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]], shape=(4, 1), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)


## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [50]:
@tf.function
def prediction(x, w, b):    
    xw_matmul = tf.matmul(x, w)
    y = tf.add(xw_matmul, b)    
    return y

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [53]:
@tf.function
def loss(y_actual, y_predicted):
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [54]:
def train(x, y_actual, w, b, learning_rate=0.01):
  with tf.GradientTape() as t:
    t.watch([w,b])
    current_prediction = prediction(X,w,b)
    current_loss = loss(y_actual, current_prediction)
    dw,db = t.gradient(current_loss, [w,b])
    w = w - learning_rate*dw
    b = b - learning_rate*db
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [55]:
for i in range(100):
    w, b = train(X,df_label, w, b, learning_rate=0.01)
    print('Current Loss on iteration', i, 
          loss(df_label, prediction(X, w, b)).numpy())

Current Loss on iteration 0 236.16774
Current Loss on iteration 1 235.09312
Current Loss on iteration 2 234.06105
Current Loss on iteration 3 233.06989
Current Loss on iteration 4 232.11801
Current Loss on iteration 5 231.20384
Current Loss on iteration 6 230.32588
Current Loss on iteration 7 229.48273
Current Loss on iteration 8 228.67294
Current Loss on iteration 9 227.89528
Current Loss on iteration 10 227.14842
Current Loss on iteration 11 226.43115
Current Loss on iteration 12 225.74232
Current Loss on iteration 13 225.08076
Current Loss on iteration 14 224.4454
Current Loss on iteration 15 223.83525
Current Loss on iteration 16 223.24927
Current Loss on iteration 17 222.68648
Current Loss on iteration 18 222.14601
Current Loss on iteration 19 221.62694
Current Loss on iteration 20 221.12846
Current Loss on iteration 21 220.64972
Current Loss on iteration 22 220.18993
Current Loss on iteration 23 219.74837
Current Loss on iteration 24 219.32433
Current Loss on iteration 25 218.917

### Observe values of Weight
- Print the updated values

In [59]:
print('Weights', w.numpy())

Weights [[0.0547828 ]
 [0.0548819 ]
 [0.05422734]
 [0.05533116]]


### Observe values of Bias
- Print the updated values

In [60]:
print('Bias',b.numpy())

Bias [4.607657]
